title: "Laila's AI Blog"
description: "AI Projects in Arabic and English"
url: "https://lailamb.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

markdown: kramdown
highlighter: rouge

minimal_mistakes_skin: "default"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: false

