title: "Laila's AI Blog"
description: "AI Projects in Arabic and English"
url: "https://lailamb.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

markdown: kramdown
highlighter: rouge


# Site-wide
locale: en
permalink: /:categories/:year/:month/:day/:title/


minimal_mistakes_skin: "default"

# Language defaults by folder
defaults:
  - scope: { path: "_posts/en" }
    values:
      lang: en
      permalink: /en/:year/:month/:day/:title/
      author_profile: true
      layout: single
  - scope: { path: "_posts/ar" }
    values:
      lang: ar
      direction: rtl
      permalink: /ar/:year/:month/:day/:title/
      author_profile: true
      layout: single


author:
  name   : "Laila"
  avatar : "/assets/images/profile.png"
  bio    : "AI Researcher"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/lailamb"
