title: "Laila's AI Blog"
description: "AI Projects in Arabic and English"
url: "https://lailamb.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

markdown: kramdown
highlighter: rouge

minimal_mistakes_skin: "default"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: home
      author_profile: true


author:
  name   : "Laila"
  avatar : "/assets/images/profile.png"
  bio    : "AI Researcher"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/lailamb"
